### ISSUE TITLE
Implement support for commands

### ISSUE THREAD

**Issue by oubiwann** [oubiwann/lcli#8]
Figure out the cleanest way to maximally use the Erlang getopt library and support commands at the same time.

Investigation:
* [x] Explore spec definitions
* [x] Explore nesting
* [x] Explore using opts as part of commands
* [x] Examine help text generation

Features:
* [x] Expand data types
  * [x] Support maps internally
  * [x] Define records
  * [x] #21
* [x] Improve getopt experience
  * [x] Override getopt default display
  * [x] Create new release of getopt that exports needed functions
* [x] Generate help text
  * [x] Create help template
  * [x] Support rendering help text with templates (mustache)
  * [x] Support rending args in help text
  * [x] Support generating help for one command
  * [x] Support generating help for all commands
* [ ] Update parser
  * [x] Refactor to use a results record
  * [x] Ensure proper parsing of args
  * [x] #23
  * [x] Parse command
  * [ ] Parse command lists
  * [ ] Parse app
  * [ ] Unify parsed options
* [ ] Implement runner support
  * [ ] Define execution context for runners (what args should always be passed)
  * [ ] Support execution of configured functions

Documentation:
* [x] #9 
* [ ] Document simple usage (a script with some flags)
* [ ] Document simple usage with non-flag args 
* [ ] Document simple multi-command usage
* [ ] Document big app usage
* [ ] Move exploratory examples into own subdir
* [ ] Add simple command example
* [ ] Add subcommands example
* [ ] Add deeply nested example

Testing:
* [x] #12
